package livro.jogo.enums;

public enum ResultadoBatalha {
    INICIO,
    PERSONAGEM_GANHOU_TURNO,
    PERSONAGEM_PERDEU_TURNO,
    EMPATE_TURNO,
    PERSONAGEM_MORTO,
    INIMIGO_MORTO,
    INIMIGO_VIVO,
    PERSONAGEM_SORTUDO,
    PERSONAGEM_AZARADO
}
